/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    network.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "7cc654104236b2ac726c804c5d7f201e2afd1c79"
 * GIT_BRANCH      "STAI-4.0"
 * GIT_DESCRIPTION "STAI-3.0.0-254-g7cc65410"
 *
 * Command Line options:
 * --load-mdesc-file = "/app/stm32ai/Utilities/configs/stm32n6"
 * --load-cdesc-file = "/app/stm32ai/Utilities/configs/cortex-m55"
 * --load-mpool-file = "/app/stm32ai/Utilities/linux/targets/stm32/resources/NPU/STM32N6xx/stm32n6"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "/tmp/stm32ai_service/02e512c0-df41-4c18-8db6-c2d1bdb47530/output/meteo_h1_npu_model_OE_3_3_1_Q.json"
 * --optimization = 3
 * --Os = true
 * --Omax-ca-pipe = 4
 * --Ocache-opt = true
 * --enable-epoch-controller = true
 * --output-info-file = "c_info"
 * --onnx-input = "/tmp/stm32ai_service/02e512c0-df41-4c18-8db6-c2d1bdb47530/output/meteo_h1_npu_model_OE_3_3_1.onnx"
 * --out-dir-prefix = "/tmp/stm32ai_service/02e512c0-df41-4c18-8db6-c2d1bdb47530/workspace/neural_art__network/"
 * --network-name = "network"
 * --generate-stai = true
 * --Oauto-sched = true
 * --Oshuffle-dma = true
 *
 * auto* option expanded into:
 *   alt-scheduler = false
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"
#include "ecloader.h"
#include "ll_aton_cipher.h"

#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 3 || LL_ATON_VERSION_DEV != 262
#  error "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* Demo/debug build:
 * keep the weights blob in AXISRAM2/ROM to avoid the 0x71000000 XSPI/GDB
 * collision, and mirror that base here so the generated network stays usable
 * without regenerating the whole CubeMX project. */
#define NETWORK_WEIGHTS_BASE_ADDR (0x34100000UL)

/* EC blob vient de network_ecblobs.h (ROM) */

/* global pool 8 is 3.14 KB */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x71000000  absolute_mode size=117440504 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
/* global pool 7 is ? */
/* index=7 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=33554424 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 1 is 643 B */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x342e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x34270000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM3 name=npuRAM3 offset=0x34200000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x34350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 11 is 1.88 MB */
/* index=11 file postfix=AXISRAM2_AXISRAM3_AXISRAM4_AXISRAM5_AXISRAM6 name=cpuRAM2_npuRAM3_npuRAM4_npuRAM5_npuRAM6 offset=0x34100000  absolute_mode size=2883576 vpool READ_WRITE THROUGHPUT=HIGH LATENCY=MID byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=91  */
/* global pool 4 is ? */
/* index=4 file postfix=AXISRAM2 name=cpuRAM2 offset=0x34100000  absolute_mode size=1048576 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXISRAM1 name=cpuRAM1 offset=0x34064000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 6 is ? */
/* index=6 file postfix=AXIFLEXMEM name=flexMEM offset=0x34000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */


const LL_Streng_EncryptionTypedef *LL_ATON_WeightEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

const LL_Streng_EncryptionTypedef *LL_ATON_BlobEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

#include "network_ecblobs.h"

/* scheduling epoch=0    nodes=21  ------------------------------------------------------------------- */

// Epoch Controller Blob (name='_ec_blob_network_1') micro instructions needed

// Epoch Controller Blob (name='_ec_blob_network_1') start function
static void _ec_blob_cache_start_func_1(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance) {
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 640))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 672))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 640))) /* Equivalent hex address = 0x342e0280UL */, 32);

};


/* scheduling epoch=6    nodes=1   ------------------------------------------------------------------- */


static void LL_ATON_End_EpochBlock_6(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance)
{
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation for unaligned buffer end address (last line) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 544))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) /* Equivalent hex address = 0x342e0200UL */, 32);


/* Unit= 27 [PROCESSOR 0] */
/* kind=Softmax node=Softmax_22 */
  Softmax_integer_sw_info softmax_integer1_sw_info = {
    /* "general.input" tensor-related info: */
    .general.input.dim.tensor_b = 1,
    .general.input.dim.tensor_h = 1,
    .general.input.dim.tensor_w = 3,
    .general.input.dim.tensor_c = 1,
    .general.input.dim.num_elem = 3,
    .general.input.stride.b = 3,
    .general.input.stride.h = 3,
    .general.input.stride.w = 1,
    .general.input.stride.c = 1,
    .general.input.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 640))) /* Equivalent hex address = 0x342e0280UL */,
    .general.input.format.is_signed = 1,
    /* "is" tensor-related info: */
    .is.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(NETWORK_WEIGHTS_BASE_ADDR + 3168))) /* Equivalent hex address = 0x34100c60UL */,
    .is.format.is_signed = 0,
    .is.dim.num_elem = 1,
    /* "izp" tensor-related info: */
    .izp.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(NETWORK_WEIGHTS_BASE_ADDR + 3200))) /* Equivalent hex address = 0x34100c80UL */,
    .izp.format.is_signed = 1,
    .izp.dim.num_elem = 1,
    /* "os" tensor-related info: */
    .os.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(NETWORK_WEIGHTS_BASE_ADDR + 3184))) /* Equivalent hex address = 0x34100c70UL */,
    .os.format.is_signed = 0,
    .os.dim.num_elem = 1,
    /* "ozp" tensor-related info: */
    .ozp.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(NETWORK_WEIGHTS_BASE_ADDR + 3216))) /* Equivalent hex address = 0x34100c90UL */,
    .ozp.format.is_signed = 1,
    .ozp.dim.num_elem = 1,
    /* "scratch" tensor-related info: */
    .scratch.dim.tensor_b = 1,
    .scratch.dim.tensor_h = 1,
    .scratch.dim.tensor_w = 125,
    .scratch.dim.tensor_c = 1,
    .scratch.dim.num_elem = 125,
    .scratch.stride.b = 500,
    .scratch.stride.h = 500,
    .scratch.stride.w = 4,
    .scratch.stride.c = 4,
    .scratch.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */,
    .scratch.format.is_signed = 1,
    /* "general.output" tensor-related info: */
    .general.output.dim.tensor_b = 1,
    .general.output.dim.tensor_h = 1,
    .general.output.dim.tensor_w = 3,
    .general.output.dim.tensor_c = 1,
    .general.output.dim.num_elem = 3,
    .general.output.stride.b = 3,
    .general.output.stride.h = 3,
    .general.output.stride.w = 1,
    .general.output.stride.c = 1,
    .general.output.mem.start_offset = ((unsigned char *)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 512))) /* Equivalent hex address = 0x342e0200UL */,
    .general.output.format.is_signed = 1,
    /* Node-specific Hyper-parameters: */
    .quantized_multiplier = 1726027392,
    .left_shift = 24,
    .diff_min = -124,
    .axis = 3,
    .general.type = LL_SW_SOFTMAX,
  };

  /* Low Level SW Layer function invocation. This will exploit EmbedNets libs) */
  /* Node Softmax_22 mapped on EmbedNets (INTEGER) as Softmax | Category: Computational */
  ll_sw_forward_softmax_integer(&softmax_integer1_sw_info);
  /* *** MCU cache clean (only) operation (SW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 544))) */
  LL_ATON_Cache_MCU_Clean_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */, 544);


}

/* scheduling epoch=7    nodes=1   ------------------------------------------------------------------- */

/* scheduling DONE                 ------------------------------------------------------------------- */

const LL_ATON_RT_EpochBlockItem_t *LL_ATON_EpochBlockItems_network(void) {

  static const LL_ATON_RT_EpochBlockItem_t ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = _ec_blob_cache_start_func_1,
      .end_epoch_block = NULL,
      .blob_address = (uintptr_t)(_ec_blob_network_1_address),
      .wait_mask = 0,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_blob | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 5,
      .estimated_npu_cycles = 3328,
      .estimated_tot_cycles = 19008,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .start_epoch_block = NULL,
      .end_epoch_block = LL_ATON_End_EpochBlock_6,
      .wait_mask = 0x00000000,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_pure_sw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 6,
      .last_epoch_num = 6,
      .in_streng_mask = 0x00000000,
      .out_streng_mask = 0x00000000,
      .estimated_npu_cycles = 260,
      .estimated_tot_cycles = 260,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_13_1_1[] = { 1, 1, 1, 13 };
  static const uint32_t buff_info__mem_shape_F_1_13_1_1[] = { 1, 13, 1, 1 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 0.0556318461894989 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { -15 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_16_1_3_1[] = { 16, 3, 1, 1 };
  static const uint32_t buff_info__mem_shape_F_16_1_3_1[] = { 16, 1, 3, 1 };
  static const float buff_info_Conv2D_3_weights_quant_scale[] = { 0.00633573858067393, 0.00451267510652542, 0.00542064057663083, 0.00262108840979636, 0.00471915118396282, 0.00356206810101867, 0.00721803354099393, 0.00597948906943202, 0.0053722239099443, 0.00537756131961942, 0.00473459670320153, 0.00472481269389391, 0.00511330412700772, 0.00620980421081185, 0.0051264283247292, 0.00481602037325501 };
  static const int16_t buff_info_Conv2D_3_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_32_16_3_1[] = { 32, 3, 1, 16 };
  static const uint32_t buff_info__mem_shape_L_32_16_3_1[] = { 32, 3, 1, 16 };
  static const float buff_info_Conv2D_8_weights_quant_scale[] = { 0.00343934004195035, 0.00423395913094282, 0.00318405893631279, 0.00547576462849975, 0.00474747410044074, 0.00266309594735503, 0.00234134122729301, 0.00274024251848459, 0.00436411006376147, 0.00265903444960713, 0.00269451108761132, 0.00303844688460231, 0.00239602359943092, 0.00438679940998554, 0.003626121673733, 0.00656948424875736, 0.00164833245798945, 0.00275865918956697, 0.00269262306392193, 0.00237439712509513, 0.00331545062363148, 0.00265914644114673, 0.00292674731463194, 0.00305447215214372, 0.00189997861161828, 0.00337026151828468, 0.00317084463313222, 0.00305543234571815, 0.00353793683461845, 0.00449072383344173, 0.00181586679536849, 0.00429949862882495 };
  static const int16_t buff_info_Conv2D_8_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_16_32_3_1[] = { 16, 3, 1, 32 };
  static const uint32_t buff_info__mem_shape_M16_16_32_3_1[] = { 16, 2, 3, 1, 16 };
  static const float buff_info_Conv2D_13_weights_quant_scale[] = { 0.0038928659632802, 0.00164734071586281, 0.00400056829676032, 0.00394276063889265, 0.00552284438163042, 0.00696855364367366, 0.00443743588402867, 0.00521736918017268, 0.00357845425605774, 0.00173034588806331, 0.00273509905673563, 0.00535959051921964, 0.00538829760625958, 0.00189637753646821, 0.00361598841845989, 0.00178107223473489 };
  static const int16_t buff_info_Conv2D_13_weights_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_3_16_1_1[] = { 3, 1, 1, 16 };
  static const uint32_t buff_info__mem_shape_F_3_16_1_1[] = { 3, 16, 1, 1 };
  static const float buff_info_Gemm_19_weights_transposed_3_quant_scale[] = { 0.00830798503011465, 0.0063370056450367, 0.00398421427235007 };
  static const int16_t buff_info_Gemm_19_weights_transposed_3_quant_offset[] = { 0, 0, 0 };
  static const uint32_t buff_info__shape_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1[] = { 1 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 13,
      .offset_limit = 80,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_13_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_13_1_1,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Conv2D_3_weights",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 3072,
      .offset_end = 3120,
      .offset_limit = 3184,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_16_1_3_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_1_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_3_weights_quant_scale,
      .offset = buff_info_Conv2D_3_weights_quant_offset,
    },
    {
      .name = "Conv2D_8_weights",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 0,
      .offset_end = 1536,
      .offset_limit = 1600,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 16,
      .mem_shape = buff_info__mem_shape_L_32_16_3_1,
      .mem_ndims = 4,
      .chpos = CHPos_Last,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_16_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_8_weights_quant_scale,
      .offset = buff_info_Conv2D_8_weights_quant_offset,
    },
    {
      .name = "Conv2D_13_weights",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 1536,
      .offset_end = 3072,
      .offset_limit = 3136,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 16,
      .mem_shape = buff_info__mem_shape_M16_16_32_3_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_32_3_1,
      .per_channel = 1,
      .scale = buff_info_Conv2D_13_weights_quant_scale,
      .offset = buff_info_Conv2D_13_weights_quant_offset,
    },
    {
      .name = "Gemm_19_weights_transposed_3",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 3120,
      .offset_end = 3168,
      .offset_limit = 3232,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 16,
      .mem_shape = buff_info__mem_shape_F_3_16_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_3_16_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_19_weights_transposed_3_quant_scale,
      .offset = buff_info_Gemm_19_weights_transposed_3_quant_offset,
    },
    {
      .name = "Gemm_19_squeeze_y_5_118_atonn_internal_scale",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 3168,
      .offset_end = 3172,
      .offset_limit = 3240,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 0,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_FLOAT,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Gemm_19_squeeze_y_5_118_atonn_internal_offset",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 3200,
      .offset_end = 3201,
      .offset_limit = 3272,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Softmax_22_122_atonn_internal_scale",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 3184,
      .offset_end = 3188,
      .offset_limit = 3256,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 0,
      .Qn = 0,
      .Qunsigned = 1,
      .type = DataType_FLOAT,
      .nbits = 32,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
    {
      .name = "Softmax_22_122_atonn_internal_offset",
      .addr_base = {(unsigned char *)(NETWORK_WEIGHTS_BASE_ADDR) /* Equivalent hex address = 0x34100000UL */},
      .offset_start = 3216,
      .offset_end = 3217,
      .offset_limit = 3288,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1,
      .mem_ndims = 1,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_FXP,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_3[] = { 1, 1, 3, 1 };
  static const uint32_t buff_info__mem_shape_U_1_3[] = { 1, 3 };
  static const float buff_info_Quantize_23_out_0_quant_scale[] = { 0.00390625 };
  static const int16_t buff_info_Quantize_23_out_0_quant_offset[] = { -128 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Quantize_23_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 512,
      .offset_end = 515,
      .offset_limit = 584,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 6,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_3,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_3,
      .per_channel = 0,
      .scale = buff_info_Quantize_23_out_0_quant_scale,
      .offset = buff_info_Quantize_23_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_network(void)
{
  return NULL;
}
